default:
	echo 'Hello, world!'
lint:
        golangci-lint run ./...
test:
        go test -count=1 -race -coverprofile=coverage.out ./...
test-no-cover:
        go test -count=1 -race ./...
fmt:
        @go fmt ./...
cover:
        @go tool cover -html=coverage.out
